const userIds = Array.from({ length: 50 }, (_, index) => `u${index + 1}`);
const taskTemplates = [
  'Plan sprint priorities',
  'Review code quality',
  'Prepare project updates',
  'Test feature onboarding',
  'Improve accessibility',
  'Refine API documentation',
  'Analyze customer feedback',
  'Create onboarding checklist',
  'Review design consistency',
  'Fix production bugs',
  'Draft stakeholder summary',
  'Optimize build pipeline',
  'Check analytics dashboards',
  'Document implementation notes',
  'Run regression tests',
  'Monitor deployment health',
  'Update roadmap milestones',
  'Review communication templates',
  'Audit security settings',
  'Prepare release notes',
  'Refine UX copy',
  'Track project risks',
  'Validate mobile flows',
  'Clean up backlog items',
  'Organize design assets',
  'Review team meeting notes',
  'Plan support schedule',
  'Assess performance metrics',
  'Update environment configs',
  'Prepare training material',
  'Align with product goals',
  'Review bug triage queue',
  'Map dependency updates',
  'Draft engineering spec',
  'Confirm launch checklist',
  'Check external integrations',
  'Analyze user retention',
  'Coordinate handoff tasks',
  'Revisit feature backlog',
  'Prepare status report',
  'Review QA notes',
  'Validate data export',
  'Track repository health',
  'Research competitor features',
  'Resolve dependency warnings',
  'Outline roadmap priorities',
  'Review account access logs',
  'Check cross-browser support',
  'Update API contracts',
  'Refine dashboard filters',
  'Test notification flows',
  'Plan monthly goals',
  'Review vendor updates',
  'Prepare customer follow-up',
  'Audit compliance checklist',
  'Create automation scripts',
  'Verify permissions matrix',
  'Monitor uptime trends',
  'Review code review feedback',
  'Document incident learnings',
  'Assess resource needs',
  'Review feature adoption',
  'Verify data migration plan',
  'Prepare marketing brief',
  'Update internal wiki',
  'Benchmark new tools',
  'Check pricing assumptions',
  'Finalize launch rehearsal'
];

const summaries = [
  'Review the latest changes and capture the next steps for the team.',
  'Document current progress clearly so stakeholders can track the work.',
  'Identify the main blockers and propose a practical solution.',
  'Validate that the implementation meets the expected deliverable and quality bar.',
  'Check for gaps in the process and close them before the next milestone.',
  'Validate the task against recent customer feedback and product goals.',
  'Summarize actions taken and confirm remaining work for the next cycle.',
  'Confirm the scope, owners, and timeline before moving forward.',
  'Review the execution details and prepare any follow-up items needed.',
  'Capture a clear outcome and ensure the task is aligned with team priorities.'
];

const getDueDate = (offset: number) => {
  const date = new Date('2026-01-01T00:00:00Z');
  date.setUTCDate(date.getUTCDate() + offset);
  return date.toISOString().slice(0, 10);
};

export const DUMMY_TASKS = userIds.flatMap((userId, userIndex) =>
  Array.from({ length: 20 }, (_, taskIndex) => ({
    id: `t${userIndex * 20 + taskIndex + 1}`,
    userId,
    title: `${taskTemplates[(userIndex + taskIndex) % taskTemplates.length]} ${taskIndex + 1}`,
    summary: `${summaries[(userIndex + taskIndex) % summaries.length]} ${taskIndex + 1} of 20 for ${userId}.`,
    dueDate: getDueDate(userIndex * 8 + taskIndex * 3 + 5),
  }))
);
